'use client';

import React from 'react';
import useExportToPDF from './hooks/useExportToPDF';
import useExportToExcel from './hooks/useExportToExcel';

const MyComponent = () => {
    const data = [
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: ' شارع العربي شارع العربي شارع العربي شارع العربي شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' },
        { name: 'John Doe', age: 30, email: 'john.doe@example.com', arabicName: 'أحمد محمد', phone: '555-555-5555', address: '123 Main St, Springfield, IL', arabicAddress: 'شارع العربي' }

        // ... more data
    ];

    const columns = [
        { header: 'Name (English)', dataKey: 'name' },
        { header: 'Age', dataKey: 'age' },
        { header: 'Email', dataKey: 'email' },
        { header: 'Name (Arabic)', dataKey: 'arabicName', align: 'right' },
        { header: 'Phone', dataKey: 'phone' },
        { header: 'Address', dataKey: 'address', align: 'right' },
        { header: 'Address (Arabic)', dataKey: 'arabicAddress', align: 'right' }
    ];

    const excelColumns = [
        { header: 'Name (English)', accessor: 'name' },
        { header: 'Age', accessor: 'age' },
        { header: 'Email', accessor: 'email' },
        { header: 'Name (Arabic)', accessor: 'arabicName' },
        { header: 'Phone', accessor: 'phone' },
        { header: 'Address', accessor: 'address' },
        { header: 'Address (Arabic)', accessor: 'arabicAddress' }
    ];

    const { generatePDF } = useExportToPDF();
    const { generateExcel } = useExportToExcel();

    return (
        <div>
            <button onClick={() => generatePDF(data, columns, 'تقرير العملاء', { x: 167, y: 15 })}>Export to PDF</button>
            {/* Rest of the component */}
            <button onClick={() => generateExcel(data, excelColumns, 'تقرير العملاء')}>Export to Excel</button>
        </div>
    );
};

export default MyComponent;
